services:
  patient-service:
    build:
      context: ./patient-service #used to build the image
    image: patientservice #sets image name
    container_name: patient-service
    environment:
      SPRING_PROFILES_ACTIVE: docker #Used for telling spring which application property file to be used
    ports:
      - "4000:4000"
    networks:
      - "ps-internal"
    depends_on:
      - billing-service

  billing-service:
    build:
      context: ./billing-service #used to build the image
    image: billingservice #sets image name
    container_name: billing-service
    environment:
      SPRING_PROFILES_ACTIVE: docker #Used for telling spring which application property file to be used
    ports:
      - "9001:9001"
      - "4001:4001"
    networks:
      - "ps-internal"

  analytics-service:
    build:
      context: ./analytics-service #used to build the image
    image: analyticsservice #sets image name
    container_name: analytics-service
    environment:
      SPRING_PROFILES_ACTIVE: docker #Used for telling spring which application property file to be used
    ports:
      - "4002:4002"
    networks:
      - "ps-internal"

  postgres:
    image: postgres:16
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PatientManagementSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ps1234
      POSTGRES_DB: Patient-Management-System
    ports:
      - "5433:5432"
    networks:
      - "ps-internal"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_NODE_ID: 1
        KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#      KAFKA_CFG_NODE_ID: 0
#      KAFKA_CFG_PROCESS_ROLES: controller,broker
#      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
#      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
#      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - "ps-internal"



networks:
  ps-internal:
    driver: bridge

#  docker-compose down [command to down the service]
#  docker-compose up --build [command to build the service]